// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ebb_crossprob_cor_R
double ebb_crossprob_cor_R(int d, NumericVector bounds, NumericVector correlations);
RcppExport SEXP GBJ_ebb_crossprob_cor_R(SEXP dSEXP, SEXP boundsSEXP, SEXP correlationsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bounds(boundsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type correlations(correlationsSEXP);
    rcpp_result_gen = Rcpp::wrap(ebb_crossprob_cor_R(d, bounds, correlations));
    return rcpp_result_gen;
END_RCPP
}
